export const ALERT_LIST_REQUEST = "ALERT_LIST_REQUEST";
export const ALERT_LIST_SUCCESS = "ALERT_LIST_SUCCESS";
export const ALERT_LIST_FAIL = "ALERT_LIST_FAIL";

export const ALERT_CREATE_REQUEST = "ALERT_CREATE_REQUEST";
export const ALERT_CREATE_SUCCESS = "ALERT_CREATE_SUCCESS";
export const ALERT_CREATE_FAIL = "ALERT_CREATE_FAIL";
export const ALERT_CREATE_RESET = "ALERT_CREATE_RESET";
