export const ALERT_LIST_REQUEST = "ALERT_LIST_REQUEST";
export const ALERT_LIST_SUCCESS = "ALERT_LIST_SUCCESS";
export const ALERT_LIST_FAIL = "ALERT_LIST_FAIL";

export const ALERT_DETAILS_REQUEST = "ALERT_DETAILS_REQUEST";
export const ALERT_DETAILS_SUCCESS = "ALERT_DETAILS_SUCCESS";
export const ALERT_DETAILS_FAIL = "ALERT_DETAILS_FAIL";

export const ALERT_CREATE_REQUEST = "ALERT_CREATE_REQUEST";
export const ALERT_CREATE_SUCCESS = "ALERT_CREATE_SUCCESS";
export const ALERT_CREATE_FAIL = "ALERT_CREATE_FAIL";
export const ALERT_CREATE_RESET = "ALERT_CREATE_RESET";

export const ALERT_UPDATE_REQUEST = "ALERT_UPDATE_REQUEST";
export const ALERT_UPDATE_SUCCESS = "ALERT_UPDATE_SUCCESS";
export const ALERT_UPDATE_FAIL = "ALERT_UPDATE_FAIL";
export const ALERT_UPDATE_RESET = "ALERT_UPDATE_RESET";

export const ALERT_DELETE_REQUEST = "ALERT_DELETE_REQUEST";
export const ALERT_DELETE_SUCCESS = "ALERT_DELETE_SUCCESS";
export const ALERT_DELETE_FAIL = "ALERT_DELETE_FAIL";
