export const DATA_LIST_REQUEST = "DATA_LIST_REQUEST";
export const DATA_LIST_SUCCESS = "DATA_LIST_SUCCESS";
export const DATA_LIST_FAIL = "DATA_LIST_FAIL";

export const DATA_DASHBOARD_REQUEST = "DATA_DASHBOARD_REQUEST";
export const DATA_DASHBOARD_SUCCESS = "DATA_DASHBOARD_SUCCESS";
export const DATA_DASHBOARD_FAIL = "DATA_DASHBOARD_FAIL";

export const DATA_UPDATE_REQUEST = "DATA_UPDATE_REQUEST";
export const DATA_UPDATE_SUCCESS = "DATA_UPDATE_SUCCESS";
export const DATA_UPDATE_FAIL = "DATA_UPDATE_FAIL";

export const DATA_CREATE_REQUEST = "DATA_CREATE_REQUEST";
export const DATA_CREATE_SUCCESS = "DATA_CREATE_SUCCESS";
export const DATA_CREATE_FAIL = "DATA_CREATE_FAIL";
