export const DATA_LIST_REQUEST = "DATA_LIST_REQUEST";
export const DATA_LIST_SUCCESS = "DATA_LIST_SUCCESS";
export const DATA_LIST_FAIL = "DATA_LIST_FAIL";

export const DATA_DASHBOARD_REQUEST = "DATA_DASHBOARD_REQUEST";
export const DATA_DASHBOARD_SUCCESS = "DATA_DASHBOARD_SUCCESS";
export const DATA_DASHBOARD_FAIL = "DATA_DASHBOARD_FAIL";
