export const DEVICE_LIST_REQUEST = "DEVICE_LIST_REQUEST";
export const DEVICE_LIST_SUCCESS = "DEVICE_LIST_SUCCESS";
export const DEVICE_LIST_FAIL = "DEVICE_LIST_FAIL";

export const DEVICE_DETAILS_REQUEST = "DEVICE_DETAILS_REQUEST";
export const DEVICE_DETAILS_SUCCESS = "DEVICE_DETAILS_SUCCESS";
export const DEVICE_DETAILS_FAIL = "DEVICE_DETAILS_FAIL";
