export const WIDGET_LIST_REQUEST = "WIDGET_LIST_REQUEST";
export const WIDGET_LIST_SUCCESS = "WIDGET_LIST_SUCCESS";
export const WIDGET_LIST_FAIL = "WIDGET_LIST_FAIL";

export const WIDGET_CREATE_REQUEST = "WIDGET_CREATE_REQUEST";
export const WIDGET_CREATE_SUCCESS = "WIDGET_CREATE_SUCCESS";
export const WIDGET_CREATE_FAIL = "WIDGET_CREATE_FAIL";
export const WIDGET_CREATE_RESET = "WIDGET_UPDATE_RESET";

export const WIDGET_UPDATE_REQUEST = "WIDGET_UPDATE_REQUEST";
export const WIDGET_UPDATE_SUCCESS = "WIDGET_UPDATE_SUCCESS";
export const WIDGET_UPDATE_FAIL = "WIDGET_UPDATE_FAIL";
export const WIDGET_UPDATE_RESET = "WIDGET_UPDATE_RESET";
